name: Build & Deploy (Next.js static export)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Empêche les déploiements concurrents
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build (static export)
        run: npm run build
        # ⚠️ Important: ton next.config.js contient `output:'export'` + images unoptimized
        # Le build va générer le dossier ./out automatiquement

      - name: Add .nojekyll (Pages)
        run: |
          mkdir -p out
          echo > out/.nojekyll

      # ⬇️ Si tu utilises un domaine personnalisé, dé-commente et remplace:
      # - name: Add CNAME (custom domain)
      #   run: echo "www.ton-domaine.tld" > out/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
